# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06e8838875ff20f52a3378f2b4206164ddd7ddebff63b177d236363fa0701a973b101aca52e5c1c06cf985a05b958c3ed580a51ed7b79154c9413f7196555947

test:
  secret_key_base: deea8a6a3edf02fea9978f012efad1dada447b8af13f896c6be9a8bc0742e01c774b57f6fd6b9d78d81272956673d8c4065bcc8b10bf5c38cd41406723fd51df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
